name: CI

on:
  push:
    branches: [ main ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  IMAGE_NAME: "{{project-name}}"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Tests
        run: |
          cargo build --verbose
          cargo test --verbose

      - name: Build image
        run: docker build -t ${{env.IMAGE_NAME}} .

      - name: Tag image latest
        run: |
          docker tag ${{env.IMAGE_NAME}} ${{env.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:latest
          docker tag ${{env.IMAGE_NAME}} ${{env.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:${{github.sha}}
      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{env.DOCKER_USERNAME}}
          password: ${{env.DOCKER_PASSWORD}}

      - name: push latest
        run: |
          docker push ${{env.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:latest
          docker push ${{env.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:${{github.sha}}
